export const LOAD_START = 'LOAD_START';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_ERROR = 'LOAD_ERROR';

export const CREATE_TITLE_START = 'CREATE_TITLE_START';
export const CREATE_TITLE_SUCCESS = 'CREATE_TITLE_SUCCESS';
export const CREATE_TITLE_ERROR = 'CREATE_TITLE_ERROR';

export const LOAD_TODO_START = 'LOAD_TODO_START';
export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS';
export const LOAD_TODO_ERROR = 'LOAD_TODO_ERROR';

export const CREATE_TODO_START = 'CREATE_TODO_START';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const DELETE_TITLE_START = 'DELETE_TITLE_START';
export const DELETE_TITLE_SUCCESS = 'DELETE_TITLE_SUCCESS';
export const DELETE_TITLE_ERROR = 'DELETE_TITLE_ERROR';

export const UPDATE_TITLE_START = 'UPDATE_TITLE_START';
export const UPDATE_TITLE_SUCCESS = 'UPDATE_TITLE_SUCCESS';
export const UPDATE_TITLE_ERROR = 'UPDATE_TITLE_ERROR';

export const UPDATE_TODO_START = 'UPDATE_TODO_START';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';
